---
- name: Update the nginx configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx.base_conf_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart nginx
